spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bug_tracker?createDatabaseIfNotExist=true
    username: root
    password: Passw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

system:
  defaults:
    users:
      admin:
        email: 'admin@ktxdev.com'
        password: 'P@ssw0rd'
      user:
        email: 'user@ktxdev.com'
        password: 'Demo123'
  jwt:
    secret: '$M#h5UjccJFS^J_m'