spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bug_tracker?createDatabaseIfNotExist=true
    username: 'bugtracker'
    password: 'BGZRas$X8M'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
server:
  port: 9803

system:
  defaults:
    email: admin@ktxdev.com
    password: P@ssw0rd
  jwt:
    secret: '$M#h5UjccJFS^J_m'